/*
 * @Date: 2022-10-31 08:52:55
 * @LastEditors: CZH
 * @LastEditTime: 2022-12-07 20:17:50
 * @FilePath: /configforpagedemo/auto-imports.d.ts
 */
// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import("element-plus/es")["ElAside"];
  const ElButton: typeof import("element-plus/es")["ElButton"];
  const ElCard: typeof import("element-plus/es")["ElCard"];
  const ElContainer: typeof import("element-plus/es")["ElContainer"];
  const ElForm: typeof import("element-plus/es")["ElForm"];
  const ElFormItem: typeof import("element-plus/es")["ElFormItem"];
  const ElHeader: typeof import("element-plus/es")["ElHeader"];
  const ElIcon: typeof import("element-plus/es")["ElIcon"];
  const ElInput: typeof import("element-plus/es")["ElInput"];
  const ElMain: typeof import("element-plus/es")["ElMain"];
  const ElMenu: typeof import("element-plus/es")["ElMenu"];
  const ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
  const ElOption: typeof import("element-plus/es")["ElOption"];
  const ElRadioButton: typeof import("element-plus/es")["ElRadioButton"];
  const ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
  const ElSelect: typeof import("element-plus/es")["ElSelect"];
  const ElSlider: typeof import("element-plus/es")["ElSlider"];
  const ElTooltip: typeof import("element-plus/es")["ElTooltip"];
  const ElTreeSelect: typeof import("element-plus/es")["ElTreeSelect"];
}
export {};
