// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/basicComponents/grid/module/gridCard/card.vue')['default']
    CardBg: typeof import('./src/components/basicComponents/cell/card/cardBg.vue')['default']
    CardBox: typeof import('./src/components/basicComponents/grid/module/gridCard/module/cardBox.vue')['default']
    CardCell: typeof import('./src/components/basicComponents/cell/card/cardCell.vue')['default']
    CustomDragElement: typeof import('./src/components/basicComponents/grid/module/baseToolComponents/gridComponent/components/CustomDragElement.vue')['default']
    Editable: typeof import('./src/components/basicComponents/grid/module/baseToolComponents/editable.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    GridDesktop: typeof import('./src/components/basicComponents/grid/gridDesktop.vue')['default']
    GridItem: typeof import('./src/components/basicComponents/grid/module/baseToolComponents/gridComponent/components/GridItem.vue')['default']
    GridLayout: typeof import('./src/components/basicComponents/grid/module/baseToolComponents/gridComponent/components/GridLayout.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    IconCell: typeof import('./src/components/basicComponents/cell/icon/iconCell.vue')['default']
    InfoCard: typeof import('./src/components/basicComponents/cell/info/infoCard.vue')['default']
    InfoCell: typeof import('./src/components/basicComponents/cell/info/infoCell.vue')['default']
    InfoList: typeof import('./src/components/basicComponents/list/info/infoList.vue')['default']
    InputCell: typeof import('./src/components/basicComponents/cell/input/inputCell.vue')['default']
    InputList: typeof import('./src/components/basicComponents/list/input/inputList.vue')['default']
    LineSlideExchange: typeof import('./src/components/animate/lineSlideExchange.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    TableCell: typeof import('./src/components/basicComponents/cell/table/tableCell.vue')['default']
    TableList: typeof import('./src/components/basicComponents/list/table/tableList.vue')['default']
  }
}

export { }
