// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    Header: typeof import('./src/components/header/header.vue')['default']
    IconCell: typeof import('./src/components/basicComponents/cell/icon/iconCell.vue')['default']
    InfoCell: typeof import('./src/components/basicComponents/cell/info/infoCell.vue')['default']
    InfoList: typeof import('./src/components/basicComponents/list/info/infoList.vue')['default']
    InputCell: typeof import('./src/components/basicComponents/cell/input/inputCell.vue')['default']
    InputList: typeof import('./src/components/basicComponents/list/input/inputList.vue')['default']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    TableCell: typeof import('./src/components/basicComponents/cell/table/tableCell.vue')['default']
    TableList: typeof import('./src/components/basicComponents/list/table/tableList.vue')['default']
  }
}

export { }
